### ISSUE TITLE
the workflow is not working well..

### ISSUE THREAD

**Issue by duseYonggwan** [saulmaldonado/skip-workflow#76]
search option with "pull_request" is not working. 

( the workflow was not skipped. )

please help. thanks

============

PR title is  ```[skip-workflow] blah blah```

workflow yml is

```
...
jobs:
  build:
    name: build
    runs-on: 'ubuntu-18.04'
    steps:
      - name: skip-workflow
        uses: saulmaldonado/skip-workflow@v1.1.0
        with:
          phrase: '[skip-workflow]'
          search: '["commit_messages", "pull_request"]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

github action job log is
```
Run saulmaldonado/skip-workflow@v1.1.0
  with:
    phrase: [skip-workflow]
    search: ["commit_messages", "pull_request"]
    github-token: ***
    pr-message: title
    fail-fast: false
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_S3_URI: s3://partners.peterpanz.com
    AWS_CLOUD_FRONT_DISTRIBUTION_ID: E2VSB7ZMHXIS0W
    SLACK_WEBHOOK_URL: ***
Searching for "[skip-workflow]" in "Merge pull request #54 from peterpanz-dev/bugfix/github-action

fix ubuntu version latest to 18.04" sha: f7c47bb29500484d174d124dc00202bbec614e10
❗ "[skip-workflow]" not found in: commit message: Merge pull request #54 from peterpanz-dev/bugfix/github-action
```

**Comment by saulmaldonado** [comment]
Hey there!

You didn't include the workflow triggers in the workflow you pasted but I have an idea what going on. If your workflow has triggers for both `push` and `pull_request` like in the following, then the script won't check the pull request title or message when the workflow is triggered by a `push` to the `main` branch.
```
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
```

This is because `push` events are isolated from the pull request they were made from. `push` webhook events have no reference to the pull request they originated from making it impossible to check its message and title. I have hardcoded this into the script to prevent it from trying to find a pull request ID in the `push` event webhook. [https://github.com/saulmaldonado/skip-workflow/blob/de3d7789a1918c692d52cb8b16b6d893bba5ec49/src/searchInPullRequest.ts#L27-L29](https://github.com/saulmaldonado/skip-workflow/blob/de3d7789a1918c692d52cb8b16b6d893bba5ec49/src/searchInPullRequest.ts#L27-L29)

The pull request title and message check options were made to skip workflow runs at the **_pull request check phase_** before it gets approved for merging. As for pushes to branches (which includes merge commits), the action will only check **commit messages** for the `[skip-workflow]` phrase.

I plan on remaking the action in the future to fit more generic use cases and this is something that will be fixed. For now, there is a workaround for this.

1. Append or prefix `[skip-workflow]` to the merge commit message before merging.
```
[skip-workflow] Merge pull request #54 from peterpanz-dev/bugfix/github-action

or

Merge pull request #54 from peterpanz-dev/bugfix/github-action [skip-workflow]
```
  The action will pick up on both of these and skip the workflow.

2. Add `[skip-workflow]` to the merge commit **message body** before merging
```
Merge pull request #54 from peterpanz-dev/bugfix/github-action

fix ubuntu version latest to 18.04 [skip-workflow]
```

Other workarounds involve replacing the `push` event trigger with `pull_request.closed` which would prevent the workflow from triggering on pushes and instead of pull request merges. Don't know if your git flow would allow for this so the best workarounds are above.

Let me know if you have any other questions or run into other issues!
